language: node_js
node_js:
- "10"
cache:
  directories:
  - node_modules

install:
- npm install
- npm install -g widdershins@4.0.1

script:
- curl https://raw.githubusercontent.com/tomochain/rpc-swagger/master/swagger.yaml -o rpc.yaml
- curl https://raw.githubusercontent.com/tomochain/tomoscan/master/server/src/docs/swagger.yml -o scan.yaml
- curl https://raw.githubusercontent.com/tomochain/tomox-sdk/master/swaggerui/swagger.yaml -o tomox-sdk.yaml
- curl https://raw.githubusercontent.com/tomochain/tomomaster/master/docs/swagger.yml -o master.yaml
- widdershins --httpsnippet true --expandBody true --search true --language_tabs 'shell:cURL' 'javascript--nodejs:Node.JS' 'go:GO' 'ruby:Ruby' 'python:Python' 'java:Java' --summary rpc.yaml -o rpc.md
- widdershins --httpsnippet true --expandBody true --search true --language_tabs 'shell:cURL' 'javascript--nodejs:Node.JS' 'go:GO' 'ruby:Ruby' 'python:Python' 'java:Java' --summary tomox-sdk.yaml -o tomox-sdk.md
- widdershins --httpsnippet true --expandBody true --search true --language_tabs 'shell:cURL' 'javascript--nodejs:Node.JS' 'go:GO' 'ruby:Ruby' 'python:Python' 'java:Java' --summary scan.yaml -o scan.md
- widdershins --httpsnippet true --expandBody true --search true --language_tabs 'shell:cURL' 'javascript--nodejs:Node.JS' 'go:GO' 'ruby:Ruby' 'python:Python' 'java:Java' --summary master.yaml -o master.md
- tail -n +24 rpc.md > tmp.md && mv tmp.md rpc.md
- tail -n +24 scan.md > tmp.md && mv tmp.md scan.md
- tail -n +24 master.md > tmp.md && mv tmp.md master.md
- tail -n +24 tomox-sdk.md > tmp.md && mv tmp.md tomox-sdk.md
- cat index.md rpc.md tomox-sdk.md scan.md master.md > source/index.html.md
- node shins.js
- node buildstyle.js

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  repo: tomochain/apidocs
  local-dir: .
  target-branch: gh-pages
  fqdn: apidocs.tomochain.com
  on:
    branch: master
